### ISSUE TITLE
Creating src folder and refactoring server-side code

### ISSUE THREAD

**Issue by TheCandiko** [chingu-voyage4/Geckos-Team-20#25]
1. Create `src` folder and putting server-side coding files into there.
2. Refactoring server-side code:
    1. According to Airbnb base rules
    2. More modular folder structure and and creating config files.

**Comment by TheCandiko** [comment]
@dragonraij 
I need an approval to move forward!!! Can you take a look when you have time?

**Comment by rajpranz** [comment]
I have reviewed the changes and approved the pull request.

**Comment by rajpranz** [comment]
Left it open in case anyone else wants to add any feedback
