### ISSUE TITLE
Defining MVP and User Stories

### ISSUE THREAD

**Issue by TheCandiko** [chingu-voyage4/Geckos-Team-20#6]
We need to define MVP and User Stories for our project.

Please check these links:
1. Story Mapping: https://medium.com/@tplmaps/user-story-mapping-how-we-do-it-ce53e07bbf30
2. FreeCodeCamp Pinterest Clone Challenge:
https://www.freecodecamp.org/challenges/build-a-pinterest-clone

Please write user stories below as comments.

**Comment by rajpranz** [comment]
In our case we can start off with a "super MVP":

- A  static home page with some images displayed in card, with menu and footer
- An about page where we can write some information about site. Also with header and footer
- A static page listing list of users, again with header footer eg: https://www.pinterest.nz/html_sitemap/pinners_a.html
- Some other pages?

The next level as MVP:
- Add authentication
- Have Sign up page
- Have log in page
- Forgotten password page
- Divide website to pages which can be visited by signed in or not signed in
- change the users page to generate a list of usernames of those who have signed up

The next level:
- Users are able to create pins consisting of images, Title and descriptions and Category
- Home page shows list of recent pins and is no longer statically generated
- Users can update or delete their pins

Next Level:
- Users are able to like, comment on  and favourite other users images
- Signed in users can see their favourites
- users can sort pins by popularity, date or no of comments.
-  users can click on other user profiles and see list of their pins

This should keep us going for a while :)

**Comment by rajpranz** [comment]
These are not actual user stories, but was trying to break down the project to simple to complex components. 
Will have a look at user stories after hearing from the team ideas

**Comment by TheCandiko** [comment]
I have tried to write _User Stories_ regarding Raj's earlier post, define a MVP and possible expansions. MVP will be our first objective to complete, but we shouldn't stay there. I believe, after MVP and/or every expansion we can deploy the web application.

Is there any other feature/user story you want to add/remove?
@dragonraij @hiralmakwana30 @shalinidc 

# Glorious Pins

Full stack web application which registered users can create and share pins with other users. Pins are used to share website links among users with optional image and description details.

## User Stories

### MVP:

* _As an unauthenticated user I can..._
  - Click pins to view its details on landing page.
  - Navigate to sign up, login, about and users pages from landing page.
  - Sign-up and login with an e-mail.
  - Visit about page to get more information about web application.
  - See list of all registered users name in another page.
  - See header and footer in every page.

* _As an authenticated user I can..._
  - Create pins to share a website link with other users.
  - Add title, category, image URL and description to my pins while creating a pin or later.
  - Click any pin to view its details.
  - Edit my pin's any detail.
  - Delete my pins.
  - Visit my profile page to see all of my pins.
  - See all pins on my user home page.

### First expansion of MVP:
* _As an authenticated user I can..._
  - Visit other user's profile page to see all of their pins.
  - Drag & drop my pins to sort them.
  - Search for a pin with its title.
  - Sort pins by its title, date, category.

### Second expansion of MVP:
* _As an authenticated user I can..._
  - Like/unlike a pin with a button on pin's card to add it to my favourite pins.
  - See my liked pins on my profile page.
  - See other user's liked pins in their profile pages.

### Third expansion of MVP
* _As an authenticated user I can..._
  - Leave a comment to a pin.
  - Edit my existed comments on a pin.
  - Delete my existed comment.
  - See all of my comments in a single page.

**Comment by rajpranz** [comment]
Im quite happy with these user stories. I dont have anything to add to it at the moment

**Comment by shalinidc** [comment]
The user stories look great to get started. 👍

**Comment by TheCandiko** [comment]
Great, then!

I think, Hiral is too busy around these days. We are behind the schedule, so I accept that those user stories are agreed. Going to update charter and plan the sprint, then!

If you have any request to update one of this stories (add/edit/remove) or for any other decision, feel free to open an issue to start a discussion.

Issue closed.
