### ISSUE TITLE
Unit Testing

### ISSUE THREAD

**Issue by TheCandiko** [chingu-voyage4/Geckos-Team-20#8]
I believe, we need to do unit tests for our JS code. I didn't do unit testing before, and I don't know how should be implement it?

What do you think? What can we do?

Let the discussion begin!

@dragonraij @hiralmakwana30 @shalinidc

**Comment by rajpranz** [comment]
As we are not so familiar with testing we could add the testing later on
And initially could work on getting out mvp up and running

**Comment by rajpranz** [comment]
I had a look at some information about javascript testing.
This link has quite comprehensive information about various tools and how they are used. 

Its a long read ... be warned
https://medium.com/powtoon-engineering/a-complete-guide-to-testing-javascript-in-2017-a217b4cd5a2a

**Comment by rajpranz** [comment]
- If you require a broad API along with specific (perhaps unique) features then Mocha would be your choice as the extensibility is there
- AVA or Tape gives you the minimum requirements. Great for providing a solid minimal foundation for you to get going fast
- If you have a large project, or would like to quickly get started without much configuration, then Jest would be a solid choice

From : 
https://raygun.com/blog/javascript-unit-testing-frameworks/

**Comment by shalinidc** [comment]
I second Raj's comment. Even I am a novice in unit testing. We could probably decide on the go.
Thanks for the links Raj, it's useful to know information. 👍

**Comment by TheCandiko** [comment]
Whenever I look into job posts, I always see that testing (unit, end-2-end etc...) is always mentioned. Therefore, I'd like to give it a try and struggle testing with you guys in this voyage journey!

But for the time being it seems that it will distract us. As Raj said, we can think again after we prepared and deployed the MVP.

Until then, NO TEST! :smile:

Issue closed.
